List<Map<String, dynamic>> ticketList = [
  {
    'from': {'code': "NYC", 'name': "New-York"},
    'to': {'code': "LDN", 'name': "London"},
    'flying_time': "8H 30M",
    'date': "1 MAY",
    'departure_time': "08:00 AM",
    'seat': "23D",
  },
  {
    'from': {'code': "KUL", 'name': "Kuala Lumpur"},
    'to': {'code': "HND", 'name': "Tokyo"},
    'flying_time': "6H 45M",
    'date': "15 JUN",
    'departure_time': "11:30 PM",
    'seat': "12A",
  },
  {
    'from': {'code': "SIN", 'name': "Singapore"},
    'to': {'code': "SYD", 'name': "Sydney"},
    'flying_time': "7H 50M",
    'date': "22 JUL",
    'departure_time': "09:15 AM",
    'seat': "08F",
  },
  {
    'from': {'code': "LHR", 'name': "London"},
    'to': {'code': "CDG", 'name': "Paris"},
    'flying_time': "1H 15M",
    'date': "5 AUG",
    'departure_time': "02:00 PM",
    'seat': "21B",
  },
  {
    'from': {'code': "DXB", 'name': "Dubai"},
    'to': {'code': "MLE", 'name': "Maldives"},
    'flying_time': "4H 10M",
    'date': "12 SEP",
    'departure_time': "03:45 AM",
    'seat': "04D",
  },
  {
    'from': {'code': "SFO", 'name': "San Francisco"},
    'to': {'code': "ICN", 'name': "Seoul"},
    'flying_time': "12H 20M",
    'date': "20 OCT",
    'departure_time': "10:30 AM",
    'seat': "33K",
  },
  {
    'from': {'code': "KCH", 'name': "Kuching"},
    'to': {'code': "BKI", 'name': "Kota Kinabalu"},
    'flying_time': "1H 05M",
    'date': "10 NOV",
    'departure_time': "08:20 AM",
    'seat': "15C",
  },
  {
    'from': {'code': "FRA", 'name': "Frankfurt"},
    'to': {'code': "JFK", 'name': "New York"},
    'flying_time': "8H 15M",
    'date': "25 DEC",
    'departure_time': "01:00 PM",
    'seat': "10G",
  },
  {
    'from': {'code': "PVG", 'name': "Shanghai"},
    'to': {'code': "BKK", 'name': "Bangkok"},
    'flying_time': "4H 35M",
    'date': "05 JAN",
    'departure_time': "06:45 PM",
    'seat': "28A",
  },
  {
    'from': {'code': "MEL", 'name': "Melbourne"},
    'to': {'code': "AKL", 'name': "Auckland"},
    'flying_time': "3H 25M",
    'date': "14 FEB",
    'departure_time': "07:10 AM",
    'seat': "07D",
  },
  {
    'from': {'code': "IST", 'name': "Istanbul"},
    'to': {'code': "FOC", 'name': "Fuzhou"},
    'flying_time': "10H 40M",
    'date': "18 MAR",
    'departure_time': "11:55 PM",
    'seat': "19E",
  },
];
